FORMAT: 1A

# 我

Dashboard

# Group 我

## 我的主页 [/api/fetchMyData]

### 我的主页 [POST]

+ method (string) - 调用方法名
+ userId (string) - 用户ID
#### 返回格式
+ name (string) - 用户真实姓名
+ gender (string) - 性别
+ birthday (string) - 用户出生日期(1980-11-11)
+ Constellation (string) - 星座
+ friendsNum (number) - 朋友数
+ attentionsNum (number) - 关注数
+ score (number) - 积分
+ gamesNum (number) - 比赛数
+ guessNum (number) - 竞猜数
+ backGroundImageUrl (string) - 背景图片
+ equipment (array) - 装备信息

+ Request (application/json)

  + Body

        {
          "method": "fetchMyData",
          "userId": "2312ssadsadads"
        }

+ Response 200 (application/json)

  + Body

        {
            "name": "bill kang",
            "gender": "male",
            "birthday": "1984-11-13",
            "Constellation": "处女座",
            "friendsNum": 12,
            "attentionsNum": 44,
            "score": 45,
            "gamesNum": 88,
            "guessNum": 222,
            "backGroundImageUrl": "http://img.pclady.com.cn/images/autovideo/autovideo/20131/8/13576226503256330.jpg",
            "equipment": [
            {
              id:1,
              imgUrl: "http://img5.imgtn.bdimg.com/it/u=4008202820,2892448099&fm=21&gp=0.jpg"
              logo:"阿迪王",
              size: 34,
              price: 123
            },
            {
              id:2,
              imgUrl: "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"
              logo:"阿迪王",
              size: 12,
              price: 321
            }
            ]
        }

## 我的主页 [/api/updateMySettings]

### 更新个人信息 [POST]

+ method (string) - 调用方法名
+ userId (string) - 用户ID
+ name (string) - 用户真实姓名
+ gender (string) - 性别
+ birthday (string) - 用户出生日期(1980-11-11)
+ email (string) - 邮箱
+ Rank (number) -信用等级
+ TechRank (number) - 网球等级
+ SelfTechRank (number) - 自我评价
+ OtherTechRank (number) - 队友评价
+ startYear (number) - 网球元年
+ hand (number) - 持拍 1左手 2 右手
+ habit (number) - 持拍方式 0 单手正拍 1 双手正拍 2 单手反拍 3 双手反拍
+ height (number) - 身高
+ weight (number) - 体重
+ address (array) - 地址List

+ Request (application/json)

  + Body

        {
          "method": "fetchMySettings",
          "userId": "2312ssadsadads",
           "name": "billkang",
              "email": "team@qq.com",
              "gender": "male",
              "birthday": "1984-11-13",
              "Rank": "优秀",
              "TechRank": 4.5,
              "SelfTechRank": 4,
              "OtherTechRank": 5,
              "startYear": 2008,
              "hand": 1,
              "habit": 1,
              "height": 160,
              "weight": 50,
              "address": [{
                "name": "A",
                "phone": "12312341231",
                "district": "四川省 成都市 锦江区",
                "detailAddress": "我不告诉你",
                "post": "110026"
              }, {
                "name": "B",
                "phone": "12312341232",
                "district": "四川省 成都市 锦江区",
                "detailAddress": "我不告诉你",
                "post": "110026"
              }, {
                "name": "C",
                "phone": 333333333,
                "district": "四川省 成都市 锦江区",
                "detailAddress": "我不告诉你",
                "post": "110026"
              }]
        }

+ Response 200 (application/json)

  + Body

{
  "code": 0,
  "errorMsg": "",
  "data": {
      result: true
  }
}

## 拉取个人设置信息 [/api/fetchMySettings]

### 拉取个人设置信息 [POST]

+ method (string) - 调用方法名
+ userId (string) - 用户ID
#### 返回格式
+ name (string) - 用户真实姓名
+ gender (string) - 性别
+ birthday (string) - 用户出生日期(1980-11-11)
+ email (string) - 邮箱
+ Rank (number) -信用等级
+ TechRank (number) - 网球等级
+ SelfTechRank (number) - 自我评价
+ OtherTechRank (number) - 队友评价
+ startYear (number) - 网球元年
+ hand (number) - 持拍 1左手 2 右手
+ habit (number) - 持拍方式 0 单手正拍 1 双手正拍 2 单手反拍 3 双手反拍
+ height (number) - 身高
+ weight (number) - 体重
+ address (array) - 地址List

+ Request (application/json)

  + Body

        {
          "method": "fetchMySettings",
          "userId": "2312ssadsadads"
        }

+ Response 200 (application/json)

  + Body

{
  "code": 0,
  "errorMsg": "",
  "data": {
    "name": "billkang",
    "email": "team@qq.com",
    "gender": "male",
    "birthday": "1984-11-13",
    "Rank": "优秀",
    "TechRank": 4.5,
    "SelfTechRank": 4,
    "OtherTechRank": 5,
    "startYear": 2008,
    "hand": 1,
    "habit": 1,
    "height": 160,
    "weight": 50,
    "address": [{
      "name": "A",
      "phone": "12312341231",
      "district": "四川省 成都市 锦江区",
      "detailAddress": "我不告诉你",
      "post": "110026"
    }, {
      "name": "B",
      "phone": "12312341232",
      "district": "四川省 成都市 锦江区",
      "detailAddress": "我不告诉你",
      "post": "110026"
    }, {
      "name": "C",
      "phone": 333333333,
      "district": "四川省 成都市 锦江区",
      "detailAddress": "我不告诉你",
      "post": "110026"
    }]
  }
}

## 拉取我的比赛信息 [/api/fetchMyMatch]

### 拉取我的比赛信息 [POST]

+ method (string) - 调用方法名
+ userId (string) - 用户ID
#### 返回格式
跟 排名详细单打or双打排名tab [/rankingDetailsTab]非常相似
需要返回一个Object 包含以下字段

+ totalwl: 总计比分
+ ytdwl: 今年比分
+ singleMatch: 单打信息
  + title
  + subtitle
  + pts
  + games
      + gameTime: 比赛用时
      + matches: 比赛标题
      + teams (Array): 比赛队伍信息
        + win (Boolean): 是否取胜
        + score (Number): 得分
        + user (Array): 队员
          + username: 队员名
      + userimage: 队员头像
+ coupleMatch: 双打信息
  + title
  + subtitle
  + pts
  + games
      + gameTime: 比赛用时
      + matches: 比赛标题
      + teams (Array): 比赛队伍信息
        + win (Boolean): 是否取胜
        + score (Number): 得分
        + user (Array): 队员
          + username: 队员名
          + userimage: 队员头像

+ Request (application/json)

  + Body

        {
          "method": "fetchMyMatch",
          "userId": "2312ssadsadads"
        }

+ Response 200 (application/json)

  + Body

{
  "code": 0,
  "errorMsg": "",
  "data": {
    "ytdwl": "12 : 1",
    "totalwl": "22 : 1",
    "singleMatch": [
      {
        "title": "华侨城*东岸2016成都业余网球精英赛 成都站",
        "subtitle": "2017.2.16 - 3.16 | 青年组 | 男子单打",
        "pts": 1500,
        "games": [
          {
            "gameTime": "02:00:00",
            "matches": "第一场",
            "teams": [
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": true,
                "score": 3
              },
              {
                "users": [
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": false,
                "score": 2
              }
            ]
          },
          {
            "gameTime": "02:00:00",
            "matches": "小组资格赛",
            "teams": [
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": true,
                "score": 3
              },
              {
                "users": [
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": false,
                "score": 2
              }
            ]
          }
        ]
      },
      {
        "title": "华侨城*东岸2016成都业余网球精英赛 成都站",
        "subtitle": "2017.2.16 - 3.16 | 青年组 | 男子单打",
        "pts": 1500,
        "games": [
          {
            "gameTime": "02:00:00",
            "matches": "第一场",
            "teams": [
              {
                "users": [
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": true,
                "score": 3
              },
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": false,
                "score": 2
              }
            ]
          },
          {
            "gameTime": "02:00:00",
            "matches": "小组资格赛",
            "teams": [
              {
                "users": [
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": true,
                "score": 3
              },
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": false,
                "score": 2
              }
            ]
          }
        ]
      }
    ],
    "coupleMatch": [
      {
        "title": "华侨城*东岸2016成都业余网球精英赛 成都站",
        "subtitle": "2017.2.16 - 3.16 | 青年组 | 男子单打",
        "pts": 1500,
        "games": [
          {
            "gameTime": "02:00:00",
            "matches": "第一场",
            "teams": [
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": true,
                "score": 3
              },
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": false,
                "score": 2
              }
            ]
          },
          {
            "gameTime": "02:00:00",
            "matches": "小组资格赛",
            "teams": [
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": true,
                "score": 3
              },
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": false,
                "score": 2
              }
            ]
          }
        ]
      },
      {
        "title": "华侨城*东岸2016成都业余网球精英赛 成都站",
        "subtitle": "2017.2.16 - 3.16 | 青年组 | 男子单打",
        "pts": 1500,
        "games": [
          {
            "gameTime": "02:00:00",
            "matches": "第一场",
            "teams": [
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": true,
                "score": 3
              },
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": false,
                "score": 2
              }
            ]
          },
          {
            "gameTime": "02:00:00",
            "matches": "小组资格赛",
            "teams": [
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": true,
                "score": 3
              },
              {
                "users": [
                  {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                  {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                ],
                "win": false,
                "score": 2
              }
            ]
          }
        ]
      }
    ]
  }
}


## 拉取我的约球信息 [/api/fetchMyPractice]

### 拉取我的约球信息 [POST]

+ method (string) - 调用方法名
+ userId (string) - 用户ID
#### 返回格式
跟 拉取我的比赛信息 [/api/fetchMyMatch] 非常相似 不同之处在于少了
        "title": "华侨城*东岸2016成都业余网球精英赛 成都站",
        "subtitle": "2017.2.16 - 3.16 | 青年组 | 男子单打",
        "pts": 1500, 等信息.
需要返回一个Object 包含以下字段

+ totalwl: 总计比分
+ ytdwl: 今年比分
+ singlePractice: 单打信息
  + games
      + gameTime: 比赛用时
      + matches: 比赛标题
      + teams (Array): 比赛队伍信息
        + win (Boolean): 是否取胜
        + score (Number): 得分
        + user (Array): 队员
          + username: 队员名
      + userimage: 队员头像
+ couplePractice: 双打信息
  + games
      + gameTime: 比赛用时
      + matches: 比赛标题
      + teams (Array): 比赛队伍信息
        + win (Boolean): 是否取胜
        + score (Number): 得分
        + user (Array): 队员
          + username: 队员名
          + userimage: 队员头像

+ Request (application/json)

  + Body

        {
          "method": "fetchMyMatch",
          "userId": "2312ssadsadads"
        }

+ Response 200 (application/json)

  + Body

{
  "code": 0,
  "errorMsg": "",
  "data": {
              "ytdwl": "12 : 1",
              "totalwl": "22 : 1",
              "singlePractice": [
                {
                  "games": [
                    {
                      "gameTime": "02:00:00",
                      "matches": "第一场",
                      "teams": [
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": true,
                          "score": 3
                        },
                        {
                          "users": [
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": false,
                          "score": 2
                        }
                      ]
                    },
                    {
                      "gameTime": "02:00:00",
                      "matches": "小组资格赛",
                      "teams": [
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": true,
                          "score": 3
                        },
                        {
                          "users": [
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": false,
                          "score": 2
                        }
                      ]
                    }
                  ]
                },
                {
                  "games": [
                    {
                      "gameTime": "02:00:00",
                      "matches": "第一场",
                      "teams": [
                        {
                          "users": [
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": true,
                          "score": 3
                        },
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": false,
                          "score": 2
                        }
                      ]
                    },
                    {
                      "gameTime": "02:00:00",
                      "matches": "小组资格赛",
                      "teams": [
                        {
                          "users": [
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": true,
                          "score": 3
                        },
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": false,
                          "score": 2
                        }
                      ]
                    }
                  ]
                }
              ],
              "couplePractice": [
                {
                  "games": [
                    {
                      "gameTime": "02:00:00",
                      "matches": "第一场",
                      "teams": [
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": true,
                          "score": 3
                        },
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": false,
                          "score": 2
                        }
                      ]
                    },
                    {
                      "gameTime": "02:00:00",
                      "matches": "小组资格赛",
                      "teams": [
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": true,
                          "score": 3
                        },
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": false,
                          "score": 2
                        }
                      ]
                    }
                  ]
                },
                {
                  "games": [
                    {
                      "gameTime": "02:00:00",
                      "matches": "第一场",
                      "teams": [
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": true,
                          "score": 3
                        },
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": false,
                          "score": 2
                        }
                      ]
                    },
                    {
                      "gameTime": "02:00:00",
                      "matches": "小组资格赛",
                      "teams": [
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": true,
                          "score": 3
                        },
                        {
                          "users": [
                            {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                            {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                          ],
                          "win": false,
                          "score": 2
                        }
                      ]
                    }
                  ]
                }
              ]
            }
}

## 新增个人装备 [/api/addEquipment]

### 新增个人装备 [POST]

+ method (string) - The calling method
+ imgUrl (string) - 图片地址
+ logo (string) - 品牌名
+ size (string) - 尺码
+ price (string) - 价格

请返回该用户所有equipment(一个数组) 格式参考下方(其实与fetchMyData返回的equipment一致)


+ Request (application/json)

  + Body

        {
          "imgUrl": "http://img5.imgtn.bdimg.com/it/u=4008202820,2892448099&fm=21&gp=0.jpg",
          "logo": "阿迪王",
          "size": 34,
          "price": 123
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                   [
                       {
                         "id": 1,
                         "imgUrl": "http://img5.imgtn.bdimg.com/it/u=4008202820,2892448099&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 34,
                         "price": 123
                       },
                       {
                         "id": 2,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 3,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 4,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 5,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 6,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 7,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       }
                     ]
                }
            }

## 编辑个人装备 [/api/editEquipment]

### 编辑个人装备 [POST]

+ method (string) - The calling method
+ id (string) - 装备id
+ imgUrl (string) - 图片地址
+ logo (string) - 品牌名
+ size (string) - 尺码
+ price (string) - 价格

请返回该用户所有equipment(一个数组) 格式参考下方(其实与fetchMyData返回的equipment一致)


+ Request (application/json)

  + Body

        {
          "id": 1,
          "imgUrl": "http://img5.imgtn.bdimg.com/it/u=4008202820,2892448099&fm=21&gp=0.jpg",
          "logo": "阿迪王",
          "size": 34,
          "price": 123
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                   [
                       {
                         "id": 1,
                         "imgUrl": "http://img5.imgtn.bdimg.com/it/u=4008202820,2892448099&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 34,
                         "price": 123
                       },
                       {
                         "id": 2,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 3,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 4,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 5,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 6,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 7,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       }
                     ]
                }
            }

## 删除个人装备 [/api/deleteEquipment]

### 删除个人装备 [POST]

+ method (string) - The calling method
+ id (string) - 装备id


请返回该用户所有equipment(一个数组) 格式参考下方(其实与fetchMyData返回的equipment一致)


+ Request (application/json)

  + Body

        {
          "id": "0",
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                   [
                       {
                         "id": 1,
                         "imgUrl": "http://img5.imgtn.bdimg.com/it/u=4008202820,2892448099&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 34,
                         "price": 123
                       },
                       {
                         "id": 2,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 3,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 4,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 5,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 6,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       },
                       {
                         "id": 7,
                         "imgUrl": "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                         "logo": "阿迪王",
                         "size": 12,
                         "price": 321
                       }
                     ]
                }
            }

## 上传装备/背景图片 [/uploadEquipmentImage]

上传装备/背景图片

+ imgstr: (String, required) - base64的图片字符串
+ name: (String, required) - 图片名

### 上传图片 [POST]

+ Request (application/json)

  + Body

              {
                "imgstr": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAJYlbEtacSs2S4wwg8wRpvxNw4SCLoxuUyQwl09RoqWM3EX5n//2Q=="
                "name": "123.jpg"
              },

+ Response 200 (application/json)

  + Body

            {
              "code": 0,
              "data": {
                "ImageUrl": "http://d.hiphotos.baidu.com/image/pic/item/38dbb6fd5266d01622b0017d9f2bd40735fa353d.jpg"
              }
            }

## 更新背景图片 [/updateBGImage]

更新背景图片

+ ImageUrl: (String, required) - 图片地址
+ userId: (String, required) - 用户id

### 更新背景图片 [POST]

+ Request (application/json)

  + Body

              {
                "ImageUrl": "http://d.hiphotos.baidu.com/image/pic/item/38dbb6fd5266d01622b0017d9f2bd40735fa353d.jpg"
                "userId": "123"
              },

+ Response 200 (application/json)

  + Body

            {
              "code": 0,
              "data": {
                "result": "success"
              }
            }