# Group 赛事相关的API

## 赛事过滤条件 [/eventFilter]

需要返回一个Object 包含以下字段

+ location: 地址列表-数组
  + text: 地理名
  + value: 地理名对应的值
+ status: 状态列表-数组
  + text: 状态名
  + value: 状态名对应的值

### 获取过滤选项 [POST]

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": {
              "location": [
                  {
                      "text": "全部",
                      "value": 1
                  },
                  {
                      "text": "成都",
                      "value": 2
                  },
                  {
                      "text": "上海",
                      "value": 3
                  },
                  {
                      "text": "北京",
                      "value": 4
                  },
                  {
                      "text": "广州",
                      "value": 5
                  }
              ],
              "status": [
                  {
                      "text": "全部",
                      "value": 1
                  },
                  {
                      "text": "正在报名",
                      "value": 2
                  },
                  {
                      "text": "分配签表",
                      "value": 3
                  },
                  {
                      "text": "正在进行",
                      "value": 4
                  },
                  {
                      "text": "已完成",
                      "value": 5
                  }
              ]
          }
      }

## 赛事列表 [/events]

返回一个数组，数组中包含的Object 需要包含以下字段

+ id : (Number, required) - Event id
+ name : (String, required) - Event 名字
+ startDate : (String) - Event 开始时间
+ endDate : (String) - Event 结束时间
+ type : (String) - Event 类别
+ location : (String) - Event 地址
+ thumb: (String) - Event 标志图

### 获取赛事列表 [POST]

+ Request (application/json)

  + Body

        {
            "status": "ALL",
            "eventFilter": "ALL",
            "location": "ALL",
            "currentPage": 6,
            "limit": 30
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": [
                    {
                        "id": 1,
                        "name": "2016成都业余网球精英赛事1",
                        "startDate": "2016.04.15",
                        "endDate": "2016.04.20",
                        "type": "俱乐部",
                        "location": "四川省 成都市 锦江区 红星路1号",
                        "thumb": "http://e.hiphotos.baidu.com/news/q%3D100/sign=3abb8c8fbe389b503effe452b534e5f1/fc1f4134970a304e2975366bd6c8a786c8175ccf.jpg"
                    },
                    {
                        "id": 2,
                        "name": "2016成都业余网球精英赛事2",
                        "startDate": "2016.04.15",
                        "endDate": "2016.04.20",
                        "type": "俱乐部",
                        "location": "四川省 成都市 锦江区 红星路1号",
                        "thumb": "http://e.hiphotos.baidu.com/news/q%3D100/sign=3abb8c8fbe389b503effe452b534e5f1/fc1f4134970a304e2975366bd6c8a786c8175ccf.jpg"
                    }
                ]
            }

## 赛事详情 [/eventDetails]

返回的data字段为一个Object, 需要包含以下字段

+ id: (Number, Required) - Event id
+ name: (String, Required) - Event name
+ startDate: (String) - Event start date
+ endDate: (String) - Event end date
+ type: (String) - Event type
+ location: (String) - Event location
+ countdown: (Number) - 赛事倒计时, 以毫秒为单位的时间戳
+ banner: (Url) - 赛事背景大图
+ thumb: (Url) - 赛事Logo, 与赛事列表中显示的图为同一个
+ schedule: (Boolean) - 赛程是否可用
+ drawTable: (Boolean) - 签表是否可用
+ score: (Boolean) - 比分是否可用
+ register: (Boolean) - 是否已报名
+ friendRegisterCount: (Boolean) - 朋友报名数
+ draw: (Boolean) - 是否已签表
+ drawCountdown: (Number) - 签表倒计时, 以毫秒为单位的时间戳
+ drawId: (Boolean) - 签位码
+ registerList: (Array, String) - 已报名的比赛, 字符串数组

### 获取赛事详情 [POST]

+ Request (application/json)

        {
            "id": 1
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": {
              "id": 1,
              "thumb": "http://hbimg.b0.upaiyun.com/65ad7509d8f8ea45beb7589cca3c557d02f15ac0e9e82-QDUx6P_sq120",
              "name": "2016成都业余网球精英赛事1",
              "startDate": "2016.04.15",
              "endDate": "2016.04.20",
              "location": "四川省 成都市 锦江区 红星路1号",
              "banner": "http://hbimg.b0.upaiyun.com/02d7023e92a7227116fad577b50fbcdf0aab4e4ead0bb-lryBLC_fw658",
              "countdown": 50000,
              "drawTable": false,
              "score": false,
              "schedule": false,
              "register": false,
              "friendRegisterCount": 30,
              "drawCountdown": 50000,
              "draw": false,
              "drawId": "#2017",
              "registerList": ["青年组|精英B|女子单打", "青年组|精英B|女子双打"],
          }
      }


## 赛事评论 [/eventComments]

返回的data字段为一个Object, 需要包含以下字段

+ total: (Number) - 评论总数
+ comments: (Array) - 评论列表
  + id: (Number) - 评论ID
  + username: (String) - 评论人的用户名
  + userimage: (Url) - 评论人的头像
  + time: (String) - 评论发表时间
  + context: (String) - 评论内容
  + like: (Boolean) - 当前用户是否对该条评论点过赞
  + likeNumber: (Number) - 评论被点赞的次数

### 获取赛事评论 [POST]

+ Request (application/json)

        {
            "id": 1
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": {
              "total": 500,
              "comments": [
                  {
                      "id": 1,
                      "username": "用户名1",
                      "userimage": "http://hbimg.b0.upaiyun.com/65ad7509d8f8ea45beb7589cca3c557d02f15ac0e9e82-QDUx6P_sq120",
                      "time": "1小时前",
                      "context": "国际在线消息（记者 刘榕）：由泰国记者协会会长万猜·翁米猜率领的泰国记者协会代表团一行由中国记者协会国际联络部副主任马玉安陪同１９日前往天津参观访问。",
                      "like": true,
                      "likeNumber": 999
                  },
                  {
                      "id": 2,
                      "username": "用户名2",
                      "userimage": "http://hbimg.b0.upaiyun.com/65ad7509d8f8ea45beb7589cca3c557d02f15ac0e9e82-QDUx6P_sq120",
                      "time": "2小时前",
                      "context": "国际在线消息（记者 刘榕）：由泰国记者协会会长万猜·翁米猜率领的泰国记者协会代表团一行由中国记者协会国际联络部副主任马玉安陪同１９日前往天津参观访问。",
                      "like": false,
                      "likeNumber": 999
                  },
                  {
                      "id": 3,
                      "username": "用户名3",
                      "userimage": "http://hbimg.b0.upaiyun.com/65ad7509d8f8ea45beb7589cca3c557d02f15ac0e9e82-QDUx6P_sq120",
                      "time": "3小时前",
                      "context": "国际在线消息（记者 刘榕）：由泰国记者协会会长万猜·翁米猜率领的泰国记者协会代表团一行由中国记者协会国际联络部副主任马玉安陪同１９日前往天津参观访问。",
                      "like": true,
                      "likeNumber": 999
                  }
              ]
          }
      }

## 赛事签表 [/eventDraw]

返回code为0, data值为签位码

### 签表请求 [POST]

+ Request (application/json)

        {
            "id": 1
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": "#2102"
      }


## 赛事评论点赞 [/eventCommentLike]

返回code为0, data值为ok 时，表示点赞成功，其他值失败

### 对评论点赞 [POST]

+ Request (application/json)

        {
            "id": 1
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": "ok"
      }

## 发表评论 [/sendComment]

返回code为0, data值为ok 时，表示评论成功，其他值失败

### 发表评论 [POST]

+ Request (application/json)

        {
            "eventId": 1,
            "context": "评论内容"
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": "ok"
      }


## 赛事赞助商 [/eventSponsors]

返回的data字段为一个数组, 需要包含以下字段

+ name: (String) - 赞助商名字
+ thumb: (Url) - 赞助商图片


### 获取赛事赞助商 [POST]

+ Request (application/json)

        {
            "id": 1
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": [
              {
                  "name": "华侨城1",
                  "thumb": "http://hbimg.b0.upaiyun.com/65ad7509d8f8ea45beb7589cca3c557d02f15ac0e9e82-QDUx6P_sq120"
              },
              {
                  "name": "华侨城2",
                  "thumb": "http://hbimg.b0.upaiyun.com/65ad7509d8f8ea45beb7589cca3c557d02f15ac0e9e82-QDUx6P_sq120"
              },
              {
                  "name": "华侨城3",
                  "thumb": "http://hbimg.b0.upaiyun.com/65ad7509d8f8ea45beb7589cca3c557d02f15ac0e9e82-QDUx6P_sq120"
              }
          ]
      }

## 赛事消息 [/eventNotices]

返回的data字段为一个数组, 需要包含以下字段

+ time: (String) - 消息发布时间
+ context: (String) - 消息内容

### 获取赛事消息 [POST]

+ Request (application/json)

        {
            "id": 1
        }

+ Response 200 (application/json)

  + Body

        {
            "code": 0,
            "data": [
                {
                    "time": "2016.12.12",
                    "context": "6月20日消息1，山东济南，近百人深夜带着马扎围坐在一起，喝啤酒吃小吃，彻夜露宿街头，这不是街头小吃摊，而是家长等候赋分登记的场景。"
                },
                {
                    "time": "2016.12.11",
                    "context": "6月20日消息2，山东济南，近百人深夜带着马扎围坐在一起，喝啤酒吃小吃，彻夜露宿街头，这不是街头小吃摊，而是家长等候赋分登记的场景。"
                },
                {
                    "time": "2016.12.10",
                    "context": "6月20日消息3，山东济南，近百人深夜带着马扎围坐在一起，喝啤酒吃小吃，彻夜露宿街头，这不是街头小吃摊，而是家长等候赋分登记的场景。"
                }
            ]
        }

## 关注赛事 [/eventFollow]

返回code为0时，表示关注成功，其他值失败

### 关注赛事请求 [POST]

+ Request (application/json)

        {
            "id": 1
        }

+ Response 200 (application/json)

  + Body

        {
            "code": 0,
            "data": "ok"
        }

## 签表 [/eventDrawTable]

### 获取签表信息-小组资格赛 [POST]

返回的data字段为Object，需要包含以下字段
+ qualify: (Boolean) - 显示的是否是小组资格赛
+ match: (Array) - 比赛轮次
  + id: (Number) - 比赛轮次Id
  + text: (String) - 比赛轮次名
  + current: (Boolean) - 初次加载时是否显示为当前轮次
+ details: (Array) - 当前显示的比赛轮次详细信息
  + completed: (Boolean) - 比赛是否已经完成
  + groupName: (String) - 小组名
  + games: (Array) - 分组列表
    + qualified: (Boolean) - 是否出线
    + gameNumber: (Number) - 总局数 
    + criticalSpot: (String) - 场得分
    + criticalGame: (String) - 局得分
    + users (Array): - 队员列表单打传一个，双打传两个
      + username: (String) - 比赛人称
      + userimage: (Url) - 比赛人头像

+ Request (application/json)

  + Body

        {
            "eventId": 1, // 赛事ID
            "matchId": 2, // 比赛条件ID 资格赛，第一轮，第二轮
            "typeId": 3 // 过滤条件ID
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "errorMsg": "",
          "data": {
            "qualify": true,
            "gameName": "青年组 精英B | 女子单打",
            "matchs": [
              {"id": 1, "text": "小组资格赛", "current": true},
              {"id": 2, "text": "第一轮"},
              {"id": 3, "text": "第二轮"},
              {"id": 4, "text": "第三轮"},
              {"id": 5, "text": "半决赛"},
              {"id": 6, "text": "决赛"}
            ],
            "details": [
            {
                "complete": true,
                "groupName": "第一组",
                "games": [
                  {
                    "users": [
                      { "username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": true,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵1", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": true,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵2", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵竹3", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  }
                ]
              },
              {
                "complete": true,
                "groupName": "第一组",
                "games": [
                  {
                    "users": [
                      { "username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": true,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵1", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": true,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵2", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵竹3", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  }
                ]
              },
              {
                "complete": true,
                "groupName": "第一组",
                "games": [
                  {
                    "users": [
                      { "username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": true,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵1", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵2", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵竹3", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  }
                ]
              },
              {
                "complete": false,
                "groupName": "第一组",
                "games": [
                  {
                    "users": [
                      { "username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": true,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵1", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵2", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  },
                  {
                    "users": [
                      { "username": "陈韵竹3", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120" }
                    ],
                    "qualified": false,
                    "gameNumber": 3,
                    "criticalSpot": "3:0",
                    "criticalGame": "3:0"
                  }
                ]
              }
            ]
          }
      }


### 获取签表信息-非小组资格赛 [POST]

返回的data字段为Object，需要包含以下字段
+ qualify: (Boolean) - 显示的是否是小组资格赛
+ match: (Array) - 比赛轮次
  + id: (Number) - 比赛轮次Id
  + text: (String) - 比赛轮次名
  + current: (Boolean) - 初次加载时是否显示为当前轮次
+ details: (Array) - 当前显示的比赛轮次详细信息 3 层数组嵌套 第一层为列表本身 第二层为晋级group 第三层对两个对打的队伍 最终包含的是以下字段
  + users: (Array) - 队员列表
    + username: (String) - 比赛人名称
    + userimage: (Url) - 比赛人头像
  + win: (Boolean) - 比赛人是否胜利
  + score: (Number) - 比赛人得分

+ Request (application/json)

  + Body

        {
            "eventId": 1, // 赛事ID
            "matchId": 2, // 比赛条件ID 资格赛，第一轮，第二轮
            "typeId": 3 // 过滤条件ID
        }

+ Response 200 (application/json)

  + Body

      {
        "code": 0,
          "errorMsg": "",
          "data": {
            "qualify": false,
            "gameName": "青年组 精英B | 女子双打",
            "matchs": [
              {"id": 1, "text": "小组资格赛"},
              {"id": 2, "text": "第一轮"},
              {"id": 3, "text": "第二轮"},
              {"id": 4, "text": "第三轮", "current": true},
              {"id": 5, "text": "半决赛"},
              {"id": 6, "text": "决赛"}
            ],
            "details": [
              [
                [
                  {
                    "score": 3,
                    "win": false,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  },
                  {
                    "score": 0,
                    "win": false,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  }
                ],
                [
                  {
                    "score": 3,
                    "win": true,
                    "users": [
                      {"username": "陈韵竹1", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  },
                  {
                    "score": 0,
                    "win": false,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  }
                ]
              ],
              [
                [
                  {
                    "score": 3,
                    "win": true,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  },
                  {
                    "score": 0,
                    "win": false,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  }
                ],
                [
                  {
                    "score": 3,
                    "win": true,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  },
                  {
                    "score": 0,
                    "win": false,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  }
                ]
              ],
              [
                [
                  {
                    "score": 3,
                    "win": true,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  },
                  {
                    "score": 0,
                    "win": false,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  }
                ],
                [
                  {
                    "score": 3,
                    "win": true,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  },
                  {
                    "score": 0,
                    "win": false,
                    "users": [
                      {"username": "陈韵竹", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"},
                      {"username": "张珊", "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"}
                    ]
                  }
                ]
              ]
            ]
          }
      }


## 赛事得分 [/api/eventScore]

按比赛分组返回一个数组

+ completed (boolean): 比赛是否已完成
+ gameTime (String): 比赛用时
+ group (String): 比赛分组
+ matches (String): 比赛场次
+ status (String): 比赛状态
+ type (String): 比赛类型
+ team (Array): 比赛队伍
  + currentScore (Number): 当前得分分数
  + currentScoreWin (Boolean): 当前得分是否胜利
  + first (Boolean): 是否发球
  + score (Number): 得分
  + win (Boolean): 是否胜利
  + winGameNumber (Number): 胜利场次
  + user (Array): 队员(双打传一组数据，双打两组)
    + username (String): 用户名
    + Userimage (String): 用户头像

### 获取赛事得分列表 [POST]

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "method": "eventScore",
            "id": 1,
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": [
              {
                  "matches": "第一场",
                  "group": "精英B | 女子双打 | 小组资格赛 | 第1组",
                  "completed": true,
                  "gameTime": "01:11:06",
                  "type": 1,
                  "status": 1,
                  "team": [
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": true,
                          "score": 3,
                          "winGameNumber": 3,
                          "currentScore": "40",
                          "currentScoreWin": true,
                          "first": true
                      },
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": false,
                          "score": 2,
                          "winGameNumber": 2,
                          "currentScore": "40",
                          "currentScoreWin": false,
                          "first": false
                      }
                  ]
              },
              {
                  "matches": "第二场",
                  "group": "精英B | 女子双打 | 小组资格赛 | 第1组",
                  "completed": true,
                  "gameTime": "01:11:06",
                  "type": 2,
                  "status": 2,
                  "team": [
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": true,
                          "score": 3
                      },
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": false,
                          "score": 2
                      }
                  ]
              },
              {
                  "matches": "第三场",
                  "group": "精英B | 女子双打 | 小组资格赛 | 第1组",
                  "completed": true,
                  "gameTime": "01:11:06",
                  "type": 3,
                  "status": 3,
                  "team": [
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": true,
                          "score": 3
                      },
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": false,
                          "score": 2
                      }
                  ]
              }
          ]
      }

## 赛程过滤条件 [/api/eventScheduleFilter]

返回一个Object

+ date (Array): 日期过滤器
  + text (String): 日期显示
  + value (String): 日期值与赛程中date 过滤条件对应
+ location (Array): 地址过滤器
  + text (String): 地址显示
  + value (String): 地址值与赛程中location 过滤条件对应


### 获取赛程过滤条件 [POST]

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "id": 1
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": {
              "location": [
                  {
                      "text": "全部",
                      "value": 0
                  },
                  {
                      "text": "电子科技大学体育场一号球馆",
                      "value": 1
                  },
                  {
                      "text": "电子科技大学体育场二号球馆",
                      "value": 2
                  }
              ],
              "date": [
                  {
                      "text": "所有",
                      "value": 0
                  },
                  {
                      "text": "2017.1.12",
                      "value": 1
                  },
                  {
                      "text": "2017.2.12",
                      "value": 2
                  },
                  {
                      "text": "2017.3.12",
                      "value": 2
                  },
                  {
                      "text": "2017.4.12",
                      "value": 3
                  },
                  {
                      "text": "2017.5.12",
                      "value": 4
                  },
                  {
                      "text": "2017.6.12",
                      "value": 5
                  },
                  {
                      "text": "2017.7.12",
                      "value": 6
                  },
                  {
                      "text": "2017.8.12",
                      "value": 7
                  },
                  {
                      "text": "2017.9.12",
                      "value": 8
                  }
              ]
          }
      }


## 赛程 [/api/eventSchedule]

返回一个Array

+ completed (boolean): 比赛是否已完成
+ gameTime (String): 比赛用时
+ group (String): 比赛分组
+ matches (String): 比赛场次
+ location (String): 与location filter的value对应 
+ date (String): 与date filter的value对应 
+ team (Array): 比赛队伍
  + currentScore (Number): 当前得分分数
  + currentScoreWin (Boolean): 当前得分是否胜利
  + first (Boolean): 是否发球
  + score (Number): 得分
  + win (Boolean): 是否胜利
  + winGameNumber (Number): 胜利场次
  + user (Array): 队员(双打传一组数据，双打两组)
    + username (String): 用户名
    + Userimage (String): 用户头像

### 获取赛程列表 [POST]

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "id": 1
        }

+ Response 200 (application/json)

  + Body

      {
          "code": 0,
          "data": [
              {
                  "matches": "第一场",
                  "group": "精英B | 女子双打 | 小组资格赛 | 第1组",
                  "completed": true,
                  "gameTime": "01:11:06",
                  "date": 1,
                  "location": 1,
                  "team": [
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": true,
                          "score": 3,
                          "winGameNumber": 3,
                          "currentScore": "40",
                          "currentScoreWin": true,
                          "first": true
                      },
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": false,
                          "score": 2,
                          "winGameNumber": 2,
                          "currentScore": "40",
                          "currentScoreWin": false,
                          "first": false
                      }
                  ]
              },
              {
                  "matches": "第一场",
                  "group": "精英B | 女子双打 | 小组资格赛 | 第1组",
                  "completed": true,
                  "gameTime": "01:11:06",
                  "date": 2,
                  "location": 2,
                  "team": [
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": true,
                          "score": 3
                      },
                      {
                          "users": [
                              {
                                  "username": "陈韵竹",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              },
                              {
                                  "username": "张珊",
                                  "userimage": "http://hbimg.b0.upaiyun.com/1b27e032369e7f502535fc6a9203e5035f18d3871a2bd-8hggiJ_sq120"
                              }
                          ],
                          "win": false,
                          "score": 2
                      }
                  ]
              }
          ]
      }

## Event [/api/events/{event_id}/drawResult]

抽签结果

+ name: (String, required) - event name
+ groupMatch: (Array, required) - group match of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score
+ firstRound: (Array, required) - first of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score
+ secondRound: (Array, required) - second round of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score
+ semifinal: (Array, required) - semifinal of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score
+ final: (Array, required) - final of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score

## Event [/eventMatchInfo]

比赛详情

+ name: (String, required) - event name
+ groupMatch: (Array, required) - group match of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score
+ firstRound: (Array, required) - first of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score
+ secondRound: (Array, required) - second round of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score
+ semifinal: (Array, required) - semifinal of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score
+ final: (Array, required) - final of this event
  + member: (Array, required) - member list of this team
    + memberName: (String, required) - member name
    + memberThumb: (String, required) - member thumb image
    + menberEnglishName: (String, required) - member english name
  + score: (Number, required) - match score

### Event Draw Result [POST]

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "method": "fetchEventDrawResult",
            "eventId": 1,
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": [
                  {
                    "name": "青年组 精英B",
                    "groupMatch": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                    "firstRound": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                    "secondRound": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                    "semifinal": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                    "final": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                  },
                  {
                    "name": "女子双打",
                    "groupMatch": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                    "firstRound": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                    "secondRound": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                    "semifinal": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                    "final": [
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                      [
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 6,
                        },
                        {
                          "member": [
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                            {"memberName": "陈韵竹", "memberEnglishName": "temaChen", "memberThumb": "http://aaa.baidu.com/aa.jpg"},
                          ],
                          "score": 3,
                        },
                      ],
                    ],
                  },
                ]
            }



