<!-- include(Events.apib) -->
<!-- include(News.apib) -->
<!-- include(Register.apib) -->
<!-- include(Users.apib) -->
<!-- include(Dashboard.apib) -->
<!-- include(Rankings.apib) -->
<!-- include(Times.apib) -->
