FORMAT: 1A

# 报名

Register is a simple API allowing consumers to register by yourself.

# Group 报名

## 获取所有组别及其项目 [/api/eventGroups]

### 获取所有组别及其项目 [POST]

报名时 获取所有组别及其项目

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "method": "fetchEventGroups",
            "eventId": "eventId"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                    "groups": [
                        {
                            "id": 1,
                            "name": "青少年 钻石组",
                            "items": [
                                {
                                    "id": 1,
                                    "name": "男子单打",
                                    "price": "50.00",
                                    "needPartner": false
                                },
                                {
                                    "id": 2,
                                    "name": "女子单打",
                                    "price": "150.00",
                                    "needPartner": true
                                }
                            ]
                        },
                        {
                            "id": 2,
                            "name": "青少年 金组",
                            "items": [
                                {
                                    "id": 1,
                                    "name": "男子单打",
                                    "price": "2250.00",
                                    "needPartner": false
                                },
                                {
                                    "id": 2,
                                    "name": "女子双打",
                                    "price": "150.00",
                                    "needPartner": true
                                }
                            ]
                        },
                        {
                            "id": 3,
                            "name": "青少年 橙组",
                            "items": [
                                {
                                    "id": 1,
                                    "name": "男子单打",
                                    "price": "50.00",
                                    "needPartner": false

                                },
                                {
                                    "id": 2,
                                    "name": "女子双打",
                                    "price": "150.00",
                                    "needPartner": true
                                }
                            ]
                        },
                        {
                            "id": 4,
                            "name": "青少年 红组",
                            "items": [
                                {
                                    "id": 1,
                                    "name": "男子单打",
                                    "price": "50.00",
                                    "needPartner": false
                                },
                                {
                                    "id": 2,
                                    "name": "女子双打",
                                    "price": "150.00",
                                    "needPartner": true
                                }
                            ]
                        },
                        {
                            "id": 5,
                            "name": "元老组",
                            "items": [
                                {
                                    "id": 1,
                                    "name": "男子单打",
                                    "price": "50.00",
                                    "needPartner": false
                                },
                                {
                                    "id": 2,
                                    "name": "女子双打",
                                    "price": "150.00",
                                    "needPartner": true
                                }
                            ]
                        }
                    ]
                }
            }


## 获取该项目最新报名人员 [/api/registeredUsers]

### 获取该项目最新报名人员 [POST]

后台可以控制返回的数量(例如不超过10个)
注意 后台返回的数据格式 name 和 thumbImgUrl 为数组
单打时 数组有一个元素 双打时数组有两个元素
返回的注册日期registerDatestr 建议后台直接处理后返回显示格式
1个小时前 6个小时前 1天前 2天前 ...

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "method": "fetchRegisteredUsers",
            "eventId": "eventId",
            "groupId": "groupId",
            "itemId": "itemId"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": [
                  {
                    "name": ["用户1","用户2"],
                    "thumbImgUrl": ["http://img0.imgtn.bdimg.com/it/u=2833976744,4249581374&fm=11&gp=0.jpg"],
                    "registerDatestr": "1小时前"
                  },
                  {
                    "name": ["用户1","用户2"],
                    "thumbImgUrl": ["http://img0.imgtn.bdimg.com/it/u=2833976744,4249581374&fm=11&gp=0.jpg"],
                    "registerDatestr": "1天前"
                  }
                ]
            }

## 双打时选择搭档名单 [/api/fetchPartners]

### 双打时选择搭档名单 [POST]

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "method": "fetchPartners",
            "eventId": "eventId",
            "groupId": "groupId",
            "itemId": "itemId"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": [
                  {
                    "id": 1,
                    "name": "真实姓名",
                    "username":"用户名",
                    "phone":"1422133221"
                  },
                  {
                    "id": 2,
                    "name": "用户名",
                    "username":"用户名",
                    "phone":"1422133221"
                  }
                ]
            }

## 提交报名信息 [/api/registerEvent]

### 提交报名信息 [POST]

单打的时候 partnerId 为空字符串

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "method": "registerEvent",
            "eventId": "eventId",
            "groupId": "groupId",
            "itemId": "itemId",
            "id": "1",
            "gender": "mail/female",
            "name": "real name",
            "phone":"13456789011",
            "personCard": "1121214353455465",
            "partnerId": "21334332"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": [
                ]
            }
