FORMAT: 1A

# Times API

# Group 时光

Resources related to Times in the API.

## 获取时光页面中的个人信息 [/fetchTimeInfo]

### 获取时光页面中的个人信息 [POST]
+ userId: (String, required) - userId

+ Request (application/json)

  + Body

        {
          "method": "fetchTimeInfo",
          "userId": "2312ssadsadads"
        }


+ Response 200 (application/json)

    + Body

        {
          "code": 0,
          "errorMsg": "",
          "data": {
              "name": "bill kang",
              "gender": "male",
              "birthday": "1984-11-13",
              "Constellation": "处女座",
              "backGroundImageUrl": "http://d.hiphotos.baidu.com/image/pic/item/38dbb6fd5266d01622b0017d9f2bd40735fa353d.jpg"

          }
        }

## 分页获取时光页面中的时光信息 [/fetchTime]

### 获取时光页面中的时光信息 [POST]
+ userId: (String, required) - userId
+ currentPage: (Number, required) - 页码

注意除了传回Time数组外,还需要传一个lastPage用来标识是否为最后一页.

+ Request (application/json)

  + Body

        {
          "method": "fetchTime",
          "userId": "2312ssadsadads",
          "currentPage": 1
        }


+ Response 200 (application/json)

    + Body

{
  "code": 0,
  "errorMsg": "",
  "data": {
      "timeList": [
              {
                "id": 1,
                "type": "Message",
                "imgs": [],
                "permission": 0,
                "message": "还可以吧 打得不错, 你决定 回到他身边,但你说你会永远记得有另一个人,依然令你感到眷恋",
                "date": "12:35am"
              },
              {
                "id": 2,
                "type": "Message",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg","http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "permission": 1,
                "message":"还可以吧 打得不错",
                "date": "2016-08-12"
              },
              {
                "id": 3,
                "type": "Message",
                "imgs": [
                  "http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg",
                  "http://img5.duitang.com/uploads/item/201506/30/20150630184627_ueUQH.thumb.700_0.jpeg",
                  "http://c.hiphotos.baidu.com/image/pic/item/d439b6003af33a876bcce3f7c35c10385243b5be.jpg",
                  "http://joy.online.sh.cn/joys/gb/images/2007-08/15/xin_1808041516299711069781.jpg",
                  "http://imgsrc.baidu.com/forum/pic/item/72c13bdbb6fd526619f116deab18972bd5073628.jpg",
                  "http://p4.qhimg.com/t0108d5e8a811cfe747.png",
                  "http://p4.qhimg.com/t0108d5e8a811cfe747.png"
                ],
                "permission": 2,
                "message":"还可以吧 打得不错",
                "date": "2016-08-12"
              },
              {
                "id": 4,
                "type": "Match",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "date": "2016-04-12",
                "location": "sdfdsf address",
                "match": "单打",
                "us":"我就是我",
                "ourScore":6,
                "opponent": "不一样的烟火",
                "opponentScore": 4,
                "message":"还可以吧 打得不错",
                "permission": 3
              },
              {
                "id": 5,
                "type": "Match",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "date": "2016-05-15",
                "matchDate": "2015-05-15",
                "location": "省体育馆",
                "match": "单打",
                "us":"我就是我",
                "ourScore":6,
                "opponent": "不一样的烟火",
                "opponentScore": 5,
                "message":"一年前我就完虐张鑫,当时还可以吧 打得不错"
              },
              {
                "id": 6,
                "type": "Message",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg","http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "permission": 0,
                "message":"哦哦你的脸 回到他身边, 我们短暂的爱情,在午夜划下句点",
                "date": "2016-08-12"
              },
              {
                "id": 7,
                "type": "Message",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg","http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "permission": 1,
                "message":"还可以吧 打得不错",
                "date": "2016-08-12"
              },
              {
                "id": 8,
                "type": "Message",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "permission": 2,
                "message":"还可以吧 打得不错",
                "date": "2016-08-12"
              },
              {
                "id": 9,
                "type": "Match",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "date": "2016-04-12",
                "location": "sdfdsf address",
                "match": 1,
                "us":"我就是我",
                "ourScore":6,
                "opponent": "不一样的烟火",
                "opponentScore": 4,
                "message":"还可以吧 打得不错"
              },
              {
                "id": 10,
                "type": "Match",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "date": "2016-05-15",
                "location": "sdfdsf address",
                "match": "单打",
                "us":"我就是我",
                "ourScore":6,
                "opponent": "不一样的烟火",
                "opponentScore": 5,
                "message":"还可以吧 打得不错"
              }
      ],
    "lastPage": false
  }
}


## 添加心情 [/AddTimeMessage]

添加心情

+ type: (String, required) - Time 类型
+ imgs: (String, required) - 新增的图片
+ message: (String, required) - 说明文字
+ permission:  (Number, required) 权限 0 公开 1 朋友可见 2 仅自己可见


### 添加心情 [POST]

+ Request (application/json)

  + Body

              {
                "type": "Message",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg","http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "permission": 0,
                "message":"还可以吧 打得不错"
              },

+ Response 200 (application/json)

  + Body

            {
              "code": 0,
              "data": {
              }
            }

## 添加约球 [/AddTimeMatch]

添加约球

+ type: (String, required) - Time 类型
+ imgs: (String, required) - 新增的图片
+ message: (String, required) - 说明文字
+ date: (String, required)  "2016-04-12",
+ location: (String, required)  "地址字符串",
+ match: (String, required)  "字符串",
+ us: (String, required) "我就是我",
+ ourScore: (number, required) 6,
+ opponent: (String, required)  "不一样的烟火",
+ opponentScore: (number, required)  4,
+ message: (String, required) "还可以吧 打得不错"


### 添加约球 [POST]

+ Request (application/json)

  + Body

              {
                "type": "Match",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "date": "2016-04-12",
                "location": "sdfdsf address",
                "match": "单打",
                "us":"我就是我",
                "ourScore":6,
                "opponent": "不一样的烟火",
                "opponentScore": 4,
                "message":"还可以吧 打得不错"
              },

+ Response 200 (application/json)

  + Body

            {
              "code": 0,
              "data": {
              }
            }


## 删除时光 [/deleteTime]

删除时光

+ id: (String, required) - 删除时光的id

### 删除时光 [POST]

+ Request (application/json)

  + Body

              {
                "id": "dsnfjdsfs"
              },

+ Response 200 (application/json)

  + Body

            {
              "code": 0,
              "data": {
              }
            }
