FORMAT: 1A

# Times API

# Group 时光

Resources related to new in the API.

## 获取我的时光 [/fetchMyTimes]

### 分页获取我的时光 [POST]

+ Request (application/json)

  + Body

        {
          "method": "fetchMyTimes",
          "userId": "2312ssadsadads",
          "pagination": 1
        }


+ Response 200 (application/json)

    + Body

        {
          "code": 0,
          "errorMsg": "",
          "data": {
            "name": "bill kang",
            "gender": "male",
            "birthday": "1984-11-13",
            "Constellation": "处女座",
            "backGroundImageUrl": "http://wetennis.cn/images/Head/89F78FFA-276E-4768-BE49-A953B645D362.jpg",
            "times": [
              {
                "id": 1,
                "type": "Message",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg","http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "permission": 0,
                "message":"还可以吧 打得不错"
              },
              {
                "id": 2,
                "type": "Message",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg","http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "permission": 1,
                "message":"还可以吧 打得不错"
              },
              {
                "id": 3,
                "type": "Message",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "permission": 2,
                "message":"还可以吧 打得不错"
              },
              {
                "id": 4,
                "type": "Match",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "date": "2016-04-12",
                "location": "sdfdsf address",
                "match": "单打",
                "us":"我就是我",
                "myScore":6,
                "opponent": "不一样的烟火",
                "opponentScore": 4,
                "message":"还可以吧 打得不错"
              },
              {
                "id": 5,
                "type": "Match",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "date": "2016-05-15",
                "location": "sdfdsf address",
                "match": "单打",
                "us":"我就是我",
                "myScore":6,
                "opponent": "不一样的烟火",
                "opponentScore": 5,
                "message":"还可以吧 打得不错"
              }
            ]
          }
        }


## 添加心情 [/AddTimeMessage]

添加心情

+ type: (String, required) - Time 类型
+ imgs: (String, required) - 新增的图片
+ message: (String, required) - 说明文字
+ permission:  (Number, required) 权限 0 公开 1 朋友可见 2 仅自己可见


### 添加心情 [POST]

+ Request (application/json)

  + Body

              {
                "type": "Message",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg","http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "permission": 0,
                "message":"还可以吧 打得不错"
              },

+ Response 200 (application/json)

  + Body

            {
              "code": 0,
              "data": {
              }
            }

## 添加约球 [/AddTimeMatch]

添加约球

+ type: (String, required) - Time 类型
+ imgs: (String, required) - 新增的图片
+ message: (String, required) - 说明文字
+ date: (String, required)  "2016-04-12",
+ location: (String, required)  "地址字符串",
+ match: (String, required)  "字符串",
+ us: (String, required) "我就是我",
+ myScore: (number, required) 6,
+ opponent: (String, required)  "不一样的烟火",
+ opponentScore: (number, required)  4,
+ message: (String, required) "还可以吧 打得不错"


### 添加约球 [POST]

+ Request (application/json)

  + Body

              {
                "type": "Match",
                "imgs": ["http://img3.imgtn.bdimg.com/it/u=3111772288,2912083143&fm=21&gp=0.jpg"],
                "date": "2016-04-12",
                "location": "sdfdsf address",
                "match": "单打",
                "us":"我就是我",
                "myScore":6,
                "opponent": "不一样的烟火",
                "opponentScore": 4,
                "message":"还可以吧 打得不错"
              },

+ Response 200 (application/json)

  + Body

            {
              "code": 0,
              "data": {
              }
            }
