FORMAT: 1A

# 用户

User is a simple API allowing consumers to signin and signup.

# Group 用户

## 用户注册 [/api/signup]

### 用户注册 [POST]

+ method (string) - The calling method
+ activationCode (string) - The activationCode
+ username (string) - The user name used for login
+ password (string) - The user password
+ phone (string) - The phone number

+ Request (application/json)

  + Body

        {
            "method": "signup",
            "password": "1",
            "username": "1",
            "phone": "1",
            "activationCode": "123567"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                    "id": "user id",
                    "username": "user name",
                    "password": "user password",
                    "phone": "user phone",
                }
            }


## 用户登录 [/api/signin]

### 用户登录 [POST]

+ method (string) - The calling method
+ username (string) - The user name
+ password (string) - The user password

+ Request (application/json)

  + Body

        {
            "method": "signin",
            "username": "1",
            "password": "1"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                    "id": "user id",
                    "name": "real name",
                    "username": "user name",
                    "password": "user password",
                    "phone": "user phone",
                    "gender": "male/female",
                    "cardId": "232323198611111111",
                    "companyName": "china mobile",
                    "companyTitle": "CTO"
                }
            }


## 用户登出 [/api/logout]

### 用户登出 [POST]

退出登录

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "method": "logout"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                }
            }

## 发送短信校验码 [/api/sendActivationCode]

### 发送短信校验码 [POST]

+ method (string) - The calling method
+ phone (string) - The phone number

+ Request (application/json)

  + Body

        {
            "method": "sendActivationCode",
            "phone": "18629032103"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                }
            }


## 校验用户名是否重复 [/api/checkUserNameDuplicated]

### 校验用户名是否重复 [POST]

+ method (string) - The calling method
+ userName (string) - 用户名

+ Request (application/json)

  + Body

        {
            "method": "checkUserNameDuplicated",
            "userName": "whereyougoing"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                  "userNameDuplicated": true
                }
            }

## 校验手机号是否重复 [/api/checkPhoneDuplicated]

### 校验手机号是否重复 [POST]

+ method (string) - The calling method
+ phone (string) - 手机号

+ Request (application/json)

  + Body

        {
            "method": "checkPhoneDuplicated",
            "phone": "12345678901"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                   "phoneDuplicated": false
                }
            }


## 用户重置密码 [/api/resetPassword]

### 用户重置密码 [POST]

+ method (string) - The calling method
+ activationCode (string) - The activationCode
+ phone (string) - The phone number
+ password (string) - The user password

+ Request (application/json)

  + Body

        {
            "method": "resetPassword",
            "phone": "12345678901",
            "activationCode": "123213",
            "password": "password"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                   "resetPassword": false
                }
            }


## 读取个人用户信息 [/api/fetchUserInfo]

通过userId向服务器请求个人信息,返回内容和signin(登录)一致

### 读取个人用户信息 [POST]

+ method (string) - The calling method
+ userId (string) - The user name

+ Request (application/json)

  + Body

        {
            "method": "fetchUserInfo",
            "userId": "1sadsada213"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                    "id": "user id",
                    "name": "real name",
                    "username": "user name",
                    "password": "user password",
                    "phone": "user phone",
                    "gender": "male/female",
                    "cardId": "232323198611111111",
                    "companyName": "china mobile",
                    "companyTitle": "CTO",
                    "club": "club"
                }
            }


## 更新个人用户信息 [/api/updateUserInfo]

### 更新个人用户信息 [POST]

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "method": "updateUserInfo",
            "id": "user id",
            "name": "real name",
            "username": "user name",
            "password": "user password",
            "phone": "user phone",
            "gender": "male/female",
            "cardId": "232323198611111111",
            "companyName": "china mobile",
            "companyTitle": "CTO",
            "club": "club"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                    "id": "user id",
                    "name": "real name",
                    "username": "user name",
                    "password": "user password",
                    "phone": "user phone",
                    "gender": "male/female",
                    "cardId": "232323198611111111",
                    "companyName": "china mobile",
                    "companyTitle": "CTO",
                    "club": "club"
                }
            }
