FORMAT: 1A

# User

User is a simple API allowing consumers to signin and signup.

# Group User

Resources related to `User` in the API.

## User SignUp [/api/signup]

### SignUp [POST]

Sign up. If it's success, the front-end side will see a cookie named `user_id` with the id of logined user.

+ method (string) - The calling method
+ id (string) - The id for user
+ name (string) - The real user name
+ username (string) - The user name used for login
+ password (string) - The user password
+ phone (string) - The phone number
+ gender (string) - The gender, it's male or female

+ Request (application/json)

  + Body

        {
            "method": "signup",
            "name": "1",
            "password": "1",
            "confirmPassword": "1",
            "gender": "male",
            "username": "1",
            "phone": "1"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                    "id": "user id",
                    "name": "real name",
                    "username": "user name",
                    "password": "user password",
                    "phone": "user phone",
                    "gender": "mail/female"
                }
            }


## User SignIn [/api/signin]

### SignIn [POST]

Sign in.

+ method (string) - The calling method
+ id (string) - The id for user
+ username (string) - The user name
+ password (string) - The user password

+ Request (application/json)

  + Body

        {
            "method": "signin",
            "username": "user name",
            "password": "user password"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                    "id": "user id",
                    "name": "real name",
                    "username": "user name",
                    "password": "user password",
                    "phone": "user phone",
                    "gender": "mail/female"
                }
            }

## User Logout [/api/logout]

### Logout [POST]

Log out, we need to clear cookie after it's successful.

+ method (string) - The calling method

+ Request (application/json)

  + Body

        {
            "method": "logout"
        }

+ Response 200 (application/json)

  + Body

            {
                "code": 0,
                "errorMsg": "",
                "data": {
                }
            }
